export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAILED = 'GET_PROFILES_FAILED';

export const POST_PROFILES_REQUEST = 'POST_PROFILES_REQUEST';
export const POST_PROFILES_SUCCESS = 'POST_PROFILES_SUCCESS';
export const POST_PROFILES_FAILED = 'POST_PROFILES_FAILED';

export const GET_PRESETS_REQUEST = 'GET_PRESETS_REQUEST';
export const GET_PRESETS_SUCCESS = 'GET_PRESETS_SUCCESS';
export const GET_PRESETS_FAILED = 'GET_PRESETS_FAILED';

export const POST_PRESETS_REQUEST = 'POST_PRESETS_REQUEST';
export const POST_PRESETS_SUCCESS = 'POST_PRESETS_SUCCESS';
export const POST_PRESETS_FAILED = 'POST_PRESETS_FAILED';

export const SELECT_PROFILE = 'SELECT_PROFILE';
